name: Pull request

on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1

        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build VSIX extension file
        uses: HaaLeo/publish-vscode-extension@v0
        id: vsix-build
        with:
          dryRun: true
          pat: stub

      - name: Archive the extension build file
        uses: actions/upload-artifact@v2
        with:
          name: extension
          path: "*.vsix"
          retention-days: 1

  prow:
    name: Prow
    runs-on: ubuntu-latest
    steps:
      - uses: jpmcb/prow-github-actions@v1.1.3
        with:
          jobs: "lgtm"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
